### ISSUE TITLE
raylib3.fs:567: Undefined word

### ISSUE THREAD

**Issue by farvardin** [ArnautDaniel/gforth-raylib#1]
hello, 

which minimal gforth version is needed to run the example?

I'm using gforth-0.7.3 and here is the result of the ``gforth example-camerafree3d.fs`` command. 

```
in file included from *OS command line*:-1
in file included from example-camerafree3d.fs:4
raylib3.fs:567: Undefined word
c-function InitWindow InitWindow n n >>>s<<< -- void	( width height title -- )
Backtrace:
$7F744DCF9C90 throw 
$7F744DCF9D28 parse-libcc-type 
$7F744DCFD0F8 parse-function-types 
$7F744DCFD3A8 c-function-ft 
```

I've previously installed raylib as required in the readme

**Comment by ArnautDaniel** [comment]
Strange,  the **s** argument must only be in newer gforths.  

I believe 0.7.9 is the minimum version necessary then.  I actually had a fresh system without gforth atm so here's what I did.

Install gforth 0.7.3 through package manager
Get gforth 0.7.9 http://www.complang.tuwien.ac.at/forth/gforth/Snapshots/current/
./install-deps.sh  _(NOTE 1)_
./configure
make
sudo make install

**Install Raylib**
Get Raylib 3.5 https://github.com/raysan5/raylib/releases/tag/3.5.0
Then use this page https://github.com/raysan5/raylib/wiki/Working-on-GNU-Linux to install the shared library
Finally open gforth,  include raylib3.fs should now work.

You might not need me to say all those steps but I figure I'll document it here anyway.

(NOTE 1: This is where a big hangup might be depending on your system.  Unfortunately gforth in my experience only really installs fully on apt based systems well cause that's what the script is setup for. I could be wrong on that.)

**Comment by farvardin** [comment]
@ArnautDaniel 
thanks for the help. I understand better. 0.7.3 is the latest stable version of gforth, and 0.7.9 seems to be a development version, which is not packaged for my LinuxMint distribution.

During the configure process, it complained "GNU libtool not found", but I already have libtool 2.4.6 installed. 

I had those errors during the compilation:

```
libtool:   error: 'lib/gforth/0.7.9_20220127/amd64/libcc-named/libgfwayland.la' is not a valid libtool archive
Usage: /usr/bin/libtool [OPTION]... [MODE-ARG]...
Try 'libtool --help' for more information.
libtool:   error: 'lib/gforth/0.7.9_20220127/amd64/libcc-named/libgfvulkan.la' is not a valid libtool archive
Usage: /usr/bin/libtool [OPTION]... [MODE-ARG]...
Try 'libtool --help' for more information.
...
```

But I could install gforth 0.7.9 anyway (and could run sokoban.fs for example).

However, I've had this error with your example:

```
gforth-0.7.9_20220127-amd64 example-camerafree3d.fs 

in file included from *the terminal*:0:-94022822762447: 
in file included from *the terminal*:-1:1: 
in file included from example-camerafree3d.fs:4:9: 
raylib3.fs:1511:1: error: Invalid memory address
>>>end-c-library<<<
Backtrace:
/usr/local/share/gforth/0.7.9_20220127/libcc.fs:829:20:  0 $7FCE63E836C8 close-lib 
/usr/local/share/gforth/0.7.9_20220127/libcc.fs:887:19:  1 $7FCE63E83F28 check-c-hash 
/usr/local/share/gforth/0.7.9_20220127/libcc.fs:1116:5:  2 $7FCE63E85918 compile-wrapper-function1 
```

**Comment by ArnautDaniel** [comment]
Hmm, what stage was that first error found in?  make?  
As to the second error I think I've seen that before back when I was making the bindings but I can't remember how I fixed it.  When I get a chance this week I'll try to look into it if I can.

**Comment by farvardin** [comment]
it was during make yes (for gforth 0.7.9)

Don't worry for my part I'm just learning forth, and I was finding a way to display some pixels, but I have already much to do before :)

**Comment by ArnautDaniel** [comment]
That's great man,  have fun learning!  This lib will be a really easy way to get pixels up once you have it working too.

I'll look into this in a few days hopefully.
