### ISSUE TITLE
Is anybody working on this?

### ISSUE THREAD

**Issue by hunar1997** [ArnautDaniel/gforth-raylib#2]
Hello

I tried using this library, apparently so many changes happened since this was created, change in:
* names of alot of functions
* number of parameters of some functions
* some functions were removed
* maybe more?
I was fixing them on my machine one by one but I was stuck in some VR related functions and some errors I couldn't fix

I'm new to forth, is it easier to regenerate the lib based on raylib.h or change the resulting raylib3.fs is easier?
I tried generating it using swig but I saw maaany errors that I didn't know how to fix

I hope somebody has some time to update the codes

**Comment by ArnautDaniel** [comment]
Currently you have to use raylib 3.5 with these bindings.  When I find time I'll update them to the latest.  What's needed is a script that can take the raylib parser output and convert it into the necessary forth syntax.

Else it will always have to be done by hand,  and SWIG doesn't work without major hand editing.

**Comment by ArnautDaniel** [comment]
Also to add to this if you want to do it yourself

Generate it with swig or however,  then you have to go through every function that passes a struct and write inline C to convert it into a pointer.
```

\c Texture2D* iGenTextureCubemap(Shader shader, Texture2D map, int size, int format, Texture2D* tex){
\c Texture2D texa = GenTextureCubemap(shader, map, size, format);
\c *tex = texa; return tex; }

c-function iGenTextureCubemap iGenTextureCubemap a{*(Shader*)} a{*(Texture2D*)} n n a -- a ( shader map size format texture -- texture )

```
Here's an example.  It's really annoying.  Would be much better to work on a raylib parser method.

**Comment by hunar1997** [comment]
Hello, thanks for the quick reply .. I didn't have time to check back on it..
I'll just use an older version of raylib :) i'm lazy
