### ISSUE TITLE
Errors with lastest gforth

### ISSUE THREAD

**Issue by eosrc** [ArnautDaniel/gforth-raylib#4]
I have just installed the latest version of gforth (gforth 0.7.9_20230921) and the command

gforth example-camerafree3d.fs

gives the following error:
in file included from example-camerafree3d.fs:4:9: 
raylib3.fs:1511:1: error: open-lib failed
>>>end-c-library<<<
Backtrace:
libcc.fs:949:29:                         0 $7FE66A0C9F20 throw 
libcc.fs:1189:5:                         1 $7FE66A0CB820 compile-wrapper-function1 

with gforth 0.7.3, I have this error:

in file included from example-camerafree3d.fs:4
raylib3.fs:567: Undefined word
c-function InitWindow InitWindow n n >>>s<<< -- void	( width height title -- )
Backtrace:
$7F8E8BE58C90 throw 
$7F8E8BE58D28 parse-libcc-type 
$7F8E8BE5C0F8 parse-function-types 
$7F8E8BE5C3A8 c-function-ft 

I have installed raylib 3.5 and spent sometimes to try to fix these
problems,  but I ran out of patience.

**Comment by ArnautDaniel** [comment]
What OS are you on?

0.7.3 won't work at all so that's expected.

I'll take a look when I get a chance.

**Comment by eosrc** [comment]
xubuntu

Thanks.

**Comment by eosrc** [comment]
It must have been an issue with my installation because this morning it works fine.
I don't remember having done anything special since last time, so it was a false alarm.

thanks for your bindings.
