### ISSUE TITLE
>vector2 definition

### ISSUE THREAD

**Issue by eosrc** [ArnautDaniel/gforth-raylib#5]
Hi,

When we enter the components of a vector2, we have to reverse
the order, while for vector3, it is, I suppose, as expected.

10e 20e >vector2  ok 1
vector2>   ok f:2
f.s <2> 2.0000000000E1 1.0000000000E1  ok f:2

10e 20e 30e >vector3  ok 1
vector3>  ok f:3
f.s <3> 1.0000000000E1 2.0000000000E1 3.0000000000E1  ok f:3

brd

**Comment by ArnautDaniel** [comment]
I've been so busy lately but you are correct.  If you want to open a pull request I'll merge it,  else I'll eventually get around to going over these.  Haven't been able to use forth lately.

**Comment by eosrc** [comment]
I have given up on raylib. Maybe because I'm an old fashion C programmer but returning struct instead struct * from functions is a deal breaker.

Thank you for your time.

**Comment by ArnautDaniel** [comment]
Yep I find that frustrating too.  No problem.
